### PR TITLE
Completed step 4 for under 0.07 seconds

### PR DESCRIPTION
**Pull request by jhileman07**
Step 1 of 2 for Step 4

### CODE REVIEW

**Comment by jhileman07** [comment]
Time under 0.0001; 0.000086

## Questions
Please include the following when you are writing your PR:   
General things:   
1. What is the purpose of this PR?
Completing step 4
2. What changes did you make? Why?
Changed algorithm for step 4 to make prime numbers faster
3. What bugs did you find while testing?
none

This PR Specific:
1. How does this make the code faster? How much headroom do you have?
Optimized with Sieve of Eratosthenes algorithm, and then further optimized by skipping even numbers. Time was 0.000086.

**Comment by echavemann** [comment]
screenshot please

**Review by echavemann — APPROVED** [review]

**Comment by jhileman07** [comment]
Screenshot 2023-10-14 at 11 36 12 PM

**Comment by jhileman07** [comment]
Screenshot 2023-10-14 at 11 36 30 PM

**Pull request merged**
